#import <UIKit/UIKit.h>
#import "AppDelegate.h"
#import "BWRZQHomeViewController.h"
#import "SharedViewControllers.h"
#import "AFNetworkReachabilityManager.h"
#import "LoadConfig.h"
#import <ShareSDK/ShareSDK.h>
#import <ShareSDKConnector/ShareSDKConnector.h>
#import "WXApi.h"
#import <TencentOpenAPI/TencentOAuth.h>
#import <TencentOpenAPI/QQApiInterface.h>
#import "JPUSHService.h"
#import <UserNotifications/UserNotifications.h>
#import "WZYForeNotification.h"
#import "WXApi.h"
#import "WXApiManager.h"
#import <AlipaySDK/AlipaySDK.h>
#import "BWRZQLoginViewController.h"
#import "XHLaunchAdManager.h"
#import "BWRZQFaBuPayViewController.h"
#import <UMCommon/UMCommon.h>
#import <TJSDK/TJSDK.h>
#import <DyAdSdk/DyAdApi.h>
#import "BWRZQTaskReadViewController.h"
#import "BWRZQTaskVideoPlayerViewController.h"
#import "BWRZQTaskDetailTwoViewController.h"

@interface AppDelegate (Logs)
+ (BOOL)applicationDidfinishlaunchingwithoptionsLogs:(NSInteger)logs;
+ (BOOL)registerShareSDKLogs:(NSInteger)logs;
+ (BOOL)applicationWillResignActiveLogs:(NSInteger)logs;
+ (BOOL)applicationDidEnterBackgroundLogs:(NSInteger)logs;
+ (BOOL)applicationWillEnterForegroundLogs:(NSInteger)logs;
+ (BOOL)applicationDidBecomeActiveLogs:(NSInteger)logs;
+ (BOOL)applicationWillTerminateLogs:(NSInteger)logs;
+ (BOOL)applicationDidregisterforremotenotificationswithdevicetokenLogs:(NSInteger)logs;
+ (BOOL)applicationDidfailtoregisterforremotenotificationswitherrorLogs:(NSInteger)logs;
+ (BOOL)jpushNotificationCenterWillpresentnotificationWithcompletionhandlerLogs:(NSInteger)logs;
+ (BOOL)jpushNotificationCenterDidreceivenotificationresponseWithcompletionhandlerLogs:(NSInteger)logs;
+ (BOOL)jpushNotificationAuthorizationWithinfoLogs:(NSInteger)logs;
+ (BOOL)applicationDidreceiveremotenotificationFetchcompletionhandlerLogs:(NSInteger)logs;
+ (BOOL)applicationDidreceiveremotenotificationLogs:(NSInteger)logs;
+ (BOOL)handleNotificationLogs:(NSInteger)logs;
+ (BOOL)notificationClickLogs:(NSInteger)logs;
+ (BOOL)networkDidReceiveMessageLogs:(NSInteger)logs;
+ (BOOL)logDicLogs:(NSInteger)logs;
+ (BOOL)applicationHandleopenurlLogs:(NSInteger)logs;
+ (BOOL)applicationOpenurlSourceapplicationAnnotationLogs:(NSInteger)logs;
+ (BOOL)onRespLogs:(NSInteger)logs;
+ (BOOL)applicationOpenurlOptionsLogs:(NSInteger)logs;
+ (BOOL)removeStartViewActionLogs:(NSInteger)logs;

@end
