#import <Foundation/Foundation.h>
#import "SDWebImageCompat.h"
#import "SDImageCache.h"
#import "SDWebImageDecoder.h"
#import "UIImage+MultiFormat.h"
#import <CommonCrypto/CommonDigest.h>
#import "UIImage+GIF.h"
#import "NSData+ImageContentType.h"
#import "NSImage+WebCache.h"
#import "SDImageCacheConfig.h"

@interface SDImageCache (Logs)
+ (BOOL)sharedImageCacheLogs:(NSInteger)logs;
+ (BOOL)initLogs:(NSInteger)logs;
+ (BOOL)initWithNamespaceLogs:(NSInteger)logs;
+ (BOOL)initWithNamespaceDiskcachedirectoryLogs:(NSInteger)logs;
+ (BOOL)deallocLogs:(NSInteger)logs;
+ (BOOL)checkIfQueueIsIOQueueLogs:(NSInteger)logs;
+ (BOOL)addReadOnlyCachePathLogs:(NSInteger)logs;
+ (BOOL)cachePathForKeyInpathLogs:(NSInteger)logs;
+ (BOOL)defaultCachePathForKeyLogs:(NSInteger)logs;
+ (BOOL)cachedFileNameForKeyLogs:(NSInteger)logs;
+ (BOOL)makeDiskCachePathLogs:(NSInteger)logs;
+ (BOOL)storeImageForkeyCompletionLogs:(NSInteger)logs;
+ (BOOL)storeImageForkeyTodiskCompletionLogs:(NSInteger)logs;
+ (BOOL)storeImageImagedataForkeyTodiskCompletionLogs:(NSInteger)logs;
+ (BOOL)storeImageDataToDiskForkeyLogs:(NSInteger)logs;
+ (BOOL)diskImageExistsWithKeyCompletionLogs:(NSInteger)logs;
+ (BOOL)imageFromMemoryCacheForKeyLogs:(NSInteger)logs;
+ (BOOL)imageFromDiskCacheForKeyLogs:(NSInteger)logs;
+ (BOOL)imageFromCacheForKeyLogs:(NSInteger)logs;
+ (BOOL)diskImageDataBySearchingAllPathsForKeyLogs:(NSInteger)logs;
+ (BOOL)diskImageForKeyLogs:(NSInteger)logs;
+ (BOOL)scaledImageForKeyImageLogs:(NSInteger)logs;
+ (BOOL)queryCacheOperationForKeyDoneLogs:(NSInteger)logs;
+ (BOOL)removeImageForKeyWithcompletionLogs:(NSInteger)logs;
+ (BOOL)removeImageForKeyFromdiskWithcompletionLogs:(NSInteger)logs;
+ (BOOL)setMaxMemoryCostLogs:(NSInteger)logs;
+ (BOOL)maxMemoryCostLogs:(NSInteger)logs;
+ (BOOL)maxMemoryCountLimitLogs:(NSInteger)logs;
+ (BOOL)setMaxMemoryCountLimitLogs:(NSInteger)logs;
+ (BOOL)clearMemoryLogs:(NSInteger)logs;
+ (BOOL)clearDiskOnCompletionLogs:(NSInteger)logs;
+ (BOOL)deleteOldFilesLogs:(NSInteger)logs;
+ (BOOL)deleteOldFilesWithCompletionBlockLogs:(NSInteger)logs;
+ (BOOL)backgroundDeleteOldFilesLogs:(NSInteger)logs;
+ (BOOL)getSizeLogs:(NSInteger)logs;
+ (BOOL)getDiskCountLogs:(NSInteger)logs;
+ (BOOL)calculateSizeWithCompletionBlockLogs:(NSInteger)logs;

@end
