#import <UIKit/UIKit.h>
#import "SGPageTitleView.h"
#import "SGPageTitleButton.h"
#import "UIView+SGFrame.h"

@interface SGPageTitleView (Logs)
+ (BOOL)initWithFrameDelegateTitlenamesLogs:(NSInteger)logs;
+ (BOOL)pageTitleViewWithFrameDelegateTitlenamesLogs:(NSInteger)logs;
+ (BOOL)initializationLogs:(NSInteger)logs;
+ (BOOL)setupSubviewsLogs:(NSInteger)logs;
+ (BOOL)layoutSubviewsLogs:(NSInteger)logs;
+ (BOOL)titleArrLogs:(NSInteger)logs;
+ (BOOL)btnMArrLogs:(NSInteger)logs;
+ (BOOL)scrollViewLogs:(NSInteger)logs;
+ (BOOL)indicatorViewLogs:(NSInteger)logs;
+ (BOOL)bottomSeparatorLogs:(NSInteger)logs;
+ (BOOL)SG_widthWithStringFontLogs:(NSInteger)logs;
+ (BOOL)setupTitleButtonsLogs:(NSInteger)logs;
+ (BOOL)btnActionLogs:(NSInteger)logs;
+ (BOOL)changeSelectedButtonLogs:(NSInteger)logs;
+ (BOOL)selectedBtnCenterLogs:(NSInteger)logs;
+ (BOOL)changeIndicatorViewLocationWithButtonLogs:(NSInteger)logs;
+ (BOOL)setPageTitleViewWithProgressOriginalindexTargetindexLogs:(NSInteger)logs;
+ (BOOL)setPageEndDeceleratingwithTargetIndexLogs:(NSInteger)logs;
+ (BOOL)smallisIndicatorScrollWithProgressOriginalbtnTargetbtnLogs:(NSInteger)logs;
+ (BOOL)smallIndicatorScrollWithProgressOriginalbtnTargetbtnLogs:(NSInteger)logs;
+ (BOOL)isIndicatorScrollWithProgressOriginalbtnTargetbtnLogs:(NSInteger)logs;
+ (BOOL)indicatorScrollWithProgressOriginalbtnTargetbtnLogs:(NSInteger)logs;
+ (BOOL)isTitleGradientEffectWithProgressOriginalbtnTargetbtnLogs:(NSInteger)logs;
+ (BOOL)setIsNeedBouncesLogs:(NSInteger)logs;
+ (BOOL)setTitleColorStateNormalLogs:(NSInteger)logs;
+ (BOOL)setTitleColorStateSelectedLogs:(NSInteger)logs;
+ (BOOL)setIndicatorColorLogs:(NSInteger)logs;
+ (BOOL)setIndicatorHeightLogs:(NSInteger)logs;
+ (BOOL)setIndicatorAnimationTimeLogs:(NSInteger)logs;
+ (BOOL)setSelectedIndexLogs:(NSInteger)logs;
+ (BOOL)setResetSelectedIndexLogs:(NSInteger)logs;
+ (BOOL)setIndicatorLengthStyleLogs:(NSInteger)logs;
+ (BOOL)setIsTitleGradientEffectLogs:(NSInteger)logs;
+ (BOOL)setIsOpenTitleTextZoomLogs:(NSInteger)logs;
+ (BOOL)setTitleTextScalingLogs:(NSInteger)logs;
+ (BOOL)setIsIndicatorScrollLogs:(NSInteger)logs;
+ (BOOL)setIsShowIndicatorLogs:(NSInteger)logs;
+ (BOOL)setIsShowBottomSeparatorLogs:(NSInteger)logs;
+ (BOOL)resetTitleWithIndexNewtitleLogs:(NSInteger)logs;
+ (BOOL)setupStartColorLogs:(NSInteger)logs;
+ (BOOL)setupEndColorLogs:(NSInteger)logs;
+ (BOOL)getRGBComponentsForcolorLogs:(NSInteger)logs;

@end
