#import <Foundation/Foundation.h>
#import "SJVideoPlayerPlaybackControllerDefines.h"
#import "SJAVMediaPlaybackController.h"
#import <SJUIKit/SJRunLoopTaskQueue.h>
#import "SJRunLoopTaskQueue.h"
#import "SJAVMediaPlayer.h"
#import "SJAVMediaPlayerLoader.h" 
#import "SJVideoPlayerRegistrar.h"
#import "AVAsset+SJAVMediaExport.h"
#import "NSTimer+SJAssetAdd.h"
#import "SJAVMediaPresentController.h"
#import "SJAVMediaPlayerDefinitionLoader.h"

@interface SJAVMediaPlaybackController (Logs)
+ (BOOL)initLogs:(NSInteger)logs;
+ (BOOL)deallocLogs:(NSInteger)logs;
+ (BOOL)setPeriodicTimeIntervalLogs:(NSInteger)logs;
+ (BOOL)setMinBufferedDurationLogs:(NSInteger)logs;
+ (BOOL)errorLogs:(NSInteger)logs;
+ (BOOL)playerViewLogs:(NSInteger)logs;
+ (BOOL)playbackTypeLogs:(NSInteger)logs;
+ (BOOL)setVideoGravityLogs:(NSInteger)logs;
+ (BOOL)videoGravityLogs:(NSInteger)logs;
+ (BOOL)assetStatusLogs:(NSInteger)logs;
+ (BOOL)timeControlStatusLogs:(NSInteger)logs;
+ (BOOL)reasonForWaitingToPlayLogs:(NSInteger)logs;
+ (BOOL)currentTimeLogs:(NSInteger)logs;
+ (BOOL)durationLogs:(NSInteger)logs;
+ (BOOL)playableDurationLogs:(NSInteger)logs;
+ (BOOL)durationWatchedLogs:(NSInteger)logs;
+ (BOOL)presentationSizeLogs:(NSInteger)logs;
+ (BOOL)isReadyForDisplayLogs:(NSInteger)logs;
+ (BOOL)isPlayedLogs:(NSInteger)logs;
+ (BOOL)isReplayedLogs:(NSInteger)logs;
+ (BOOL)isPlayedToEndTimeLogs:(NSInteger)logs;
+ (BOOL)setVolumeLogs:(NSInteger)logs;
+ (BOOL)setRateLogs:(NSInteger)logs;
+ (BOOL)setMutedLogs:(NSInteger)logs;
+ (BOOL)setMediaLogs:(NSInteger)logs;
+ (BOOL)setPlayerLogs:(NSInteger)logs;
+ (BOOL)prepareToPlayLogs:(NSInteger)logs;
+ (BOOL)replayLogs:(NSInteger)logs;
+ (BOOL)refreshLogs:(NSInteger)logs;
+ (BOOL)playLogs:(NSInteger)logs;
+ (BOOL)pauseLogs:(NSInteger)logs;
+ (BOOL)stopLogs:(NSInteger)logs;
+ (BOOL)_stopLogs:(NSInteger)logs;
+ (BOOL)seekToTimeCompletionhandlerLogs:(NSInteger)logs;
+ (BOOL)seekToTimeTolerancebeforeToleranceafterCompletionhandlerLogs:(NSInteger)logs;
+ (BOOL)switchVideoDefinitionLogs:(NSInteger)logs;
+ (BOOL)_definitionSwitchingStatusDidChangeStatusLogs:(NSInteger)logs;
+ (BOOL)superviewLogs:(NSInteger)logs;
+ (BOOL)screenshotLogs:(NSInteger)logs;
+ (BOOL)presentControllerPresentviewreadyfordisplaydidchangeLogs:(NSInteger)logs;
+ (BOOL)playerAssetStatusDidChangeLogs:(NSInteger)logs;
+ (BOOL)playerTimeControlStatusDidChangeLogs:(NSInteger)logs;
+ (BOOL)playerDurationDidChangeLogs:(NSInteger)logs;
+ (BOOL)playerDidPlayToEndTimeLogs:(NSInteger)logs;
+ (BOOL)playerPresentationSizeDidChangeLogs:(NSInteger)logs;
+ (BOOL)playerPlaybackTypeDidChangeLogs:(NSInteger)logs;
+ (BOOL)playerPlayableDurationDidChangeLogs:(NSInteger)logs;
+ (BOOL)_initObservationsLogs:(NSInteger)logs;
+ (BOOL)_addPeriodicTimeObserverLogs:(NSInteger)logs;
+ (BOOL)_removePeriodicTimeObserverLogs:(NSInteger)logs;

@end
