#import <UIKit/UIKit.h>
#import "SJFitOnScreenManagerDefines.h"
#import "SJRotationManagerDefines.h"
#import "SJVideoPlayerControlLayerProtocol.h"
#import "SJControlLayerAppearManagerDefines.h"
#import "SJFlipTransitionManagerDefines.h"
#import "SJVideoPlayerPlaybackControllerDefines.h"
#import "SJVideoPlayerURLAsset+SJAVMediaPlaybackAdd.h"
#import "SJPlayerGestureControlDefines.h"
#import "SJDeviceVolumeAndBrightnessManagerDefines.h"
#import "SJFloatSmallViewControllerDefines.h"
#import "SJEdgeFastForwardViewControllerDefines.h"
#import "SJVideoDefinitionSwitchingInfo.h"
#import "SJPopPromptControllerDefines.h"
#import "SJPlaybackObservation.h"
#import "SJVideoPlayerPresentViewDefines.h"
#import "SJSubtitlesPromptControllerDefines.h"
#import "SJBarrageQueueControllerDefines.h"
#import "SJPromptDefines.h"
#import "SJBaseVideoPlayer.h"
#import <objc/message.h>
#import "SJRotationManager.h"
#import "SJDeviceVolumeAndBrightnessManager.h"
#import "SJVideoPlayerRegistrar.h"
#import "SJVideoPlayerPresentView.h"
#import "SJPlayModelPropertiesObserver.h"
#import "SJTimerControl.h"
#import "UIScrollView+ListViewAutoplaySJAdd.h"
#import "SJAVMediaPlaybackController.h"
#import "SJReachability.h"
#import "SJControlLayerAppearStateManager.h"
#import "SJFitOnScreenManager.h"
#import "SJFlipTransitionManager.h"
#import "SJPlayerView.h"
#import "SJFloatSmallViewController.h"
#import "SJEdgeFastForwardViewController.h"
#import "SJVideoDefinitionSwitchingInfo+Private.h"
#import "SJPopPromptController.h"
#import "SJPrompt.h"
#import "SJBaseVideoPlayerConst.h"
#import "SJSubtitlesPromptController.h"
#import "SJBaseVideoPlayer+TestLog.h"
#import "SJVideoPlayerURLAsset+SJSubtitlesAdd.h"
#import "SJBarrageQueueController.h"
#import "SJViewControllerManager.h"
#import "UIView+SJBaseVideoPlayerExtended.h"
#import <Masonry/Masonry.h>
#import "Masonry.h"

@interface SJBaseVideoPlayer (PlayControlLogs)
+ (BOOL)setPlaybackControllerLogs:(NSInteger)logs;
+ (BOOL)playbackControllerLogs:(NSInteger)logs;
+ (BOOL)_needUpdatePlaybackControllerPropertiesLogs:(NSInteger)logs;
+ (BOOL)playbackObserverLogs:(NSInteger)logs;
+ (BOOL)switchVideoDefinitionLogs:(NSInteger)logs;
+ (BOOL)definitionSwitchingInfoLogs:(NSInteger)logs;
+ (BOOL)_resetDefinitionSwitchingInfoLogs:(NSInteger)logs;
+ (BOOL)playbackTypeLogs:(NSInteger)logs;
+ (BOOL)errorLogs:(NSInteger)logs;
+ (BOOL)assetStatusLogs:(NSInteger)logs;
+ (BOOL)timeControlStatusLogs:(NSInteger)logs;
+ (BOOL)reasonForWaitingToPlayLogs:(NSInteger)logs;
+ (BOOL)isPlayedToEndTimeLogs:(NSInteger)logs;
+ (BOOL)isPlayedLogs:(NSInteger)logs;
+ (BOOL)isReplayedLogs:(NSInteger)logs;
+ (BOOL)currentTimeLogs:(NSInteger)logs;
+ (BOOL)durationLogs:(NSInteger)logs;
+ (BOOL)playableDurationLogs:(NSInteger)logs;
+ (BOOL)durationWatchedLogs:(NSInteger)logs;
+ (BOOL)stringForSecondsLogs:(NSInteger)logs;
+ (BOOL)setURLAssetLogs:(NSInteger)logs;
+ (BOOL)URLAssetLogs:(NSInteger)logs;
+ (BOOL)_tryToPlayIfNeededLogs:(NSInteger)logs;
+ (BOOL)_updateAssetObserversLogs:(NSInteger)logs;
+ (BOOL)refreshLogs:(NSInteger)logs;
+ (BOOL)setAssetDeallocExeBlockLogs:(NSInteger)logs;
+ (BOOL)(__kindof SJBaseVideoPlayer * _Nonnull))assetDeallocExeBlockLogs:(NSInteger)logs;
+ (BOOL)setPlayerVolumeLogs:(NSInteger)logs;
+ (BOOL)playerVolumeLogs:(NSInteger)logs;
+ (BOOL)setMutedLogs:(NSInteger)logs;
+ (BOOL)isMutedLogs:(NSInteger)logs;
+ (BOOL)setAutoplayWhenSetNewAssetLogs:(NSInteger)logs;
+ (BOOL)autoplayWhenSetNewAssetLogs:(NSInteger)logs;
+ (BOOL)setPauseWhenAppDidEnterBackgroundLogs:(NSInteger)logs;
+ (BOOL)pauseWhenAppDidEnterBackgroundLogs:(NSInteger)logs;
+ (BOOL)setResumePlaybackWhenAppDidEnterForegroundLogs:(NSInteger)logs;
+ (BOOL)resumePlaybackWhenAppDidEnterForegroundLogs:(NSInteger)logs;
+ (BOOL)setCanPlayAnAssetLogs:(NSInteger)logs;
+ (BOOL)(__kindof SJBaseVideoPlayer * _Nonnull))canPlayAnAssetLogs:(NSInteger)logs;
+ (BOOL)setResumePlaybackWhenPlayerHasFinishedSeekingLogs:(NSInteger)logs;
+ (BOOL)resumePlaybackWhenPlayerHasFinishedSeekingLogs:(NSInteger)logs;
+ (BOOL)playLogs:(NSInteger)logs;
+ (BOOL)pauseLogs:(NSInteger)logs;
+ (BOOL)stopLogs:(NSInteger)logs;
+ (BOOL)replayLogs:(NSInteger)logs;
+ (BOOL)setCanSeekToTimeLogs:(NSInteger)logs;
+ (BOOL)(__kindof SJBaseVideoPlayer * _Nonnull))canSeekToTimeLogs:(NSInteger)logs;
+ (BOOL)setAccurateSeekingLogs:(NSInteger)logs;
+ (BOOL)accurateSeekingLogs:(NSInteger)logs;
+ (BOOL)seekToTimeCompletionhandlerLogs:(NSInteger)logs;
+ (BOOL)seekToTimeTolerancebeforeToleranceafterCompletionhandlerLogs:(NSInteger)logs;
+ (BOOL)setRateLogs:(NSInteger)logs;
+ (BOOL)rateLogs:(NSInteger)logs;
+ (BOOL)_updatePlayModelObserverLogs:(NSInteger)logs;
+ (BOOL)playbackControllerAssetstatusdidchangeLogs:(NSInteger)logs;
+ (BOOL)playbackControllerTimecontrolstatusdidchangeLogs:(NSInteger)logs;
+ (BOOL)playbackControllerDurationdidchangeLogs:(NSInteger)logs;
+ (BOOL)playbackControllerCurrenttimedidchangeLogs:(NSInteger)logs;
+ (BOOL)mediaDidPlayToEndForPlaybackControllerLogs:(NSInteger)logs;
+ (BOOL)playbackControllerPresentationsizedidchangeLogs:(NSInteger)logs;
+ (BOOL)playbackControllerPlaybacktypedidchangeLogs:(NSInteger)logs;
+ (BOOL)playbackControllerPlayabledurationdidchangeLogs:(NSInteger)logs;
+ (BOOL)playbackControllerIsReadyForDisplayLogs:(NSInteger)logs;
+ (BOOL)playbackControllerSwitchingdefinitionstatusdidchangeMediaLogs:(NSInteger)logs;

@end
