#import <UIKit/UIKit.h>
#import "SJFitOnScreenManagerDefines.h"
#import "SJRotationManagerDefines.h"
#import "SJVideoPlayerControlLayerProtocol.h"
#import "SJControlLayerAppearManagerDefines.h"
#import "SJFlipTransitionManagerDefines.h"
#import "SJVideoPlayerPlaybackControllerDefines.h"
#import "SJVideoPlayerURLAsset+SJAVMediaPlaybackAdd.h"
#import "SJPlayerGestureControlDefines.h"
#import "SJDeviceVolumeAndBrightnessManagerDefines.h"
#import "SJFloatSmallViewControllerDefines.h"
#import "SJEdgeFastForwardViewControllerDefines.h"
#import "SJVideoDefinitionSwitchingInfo.h"
#import "SJPopPromptControllerDefines.h"
#import "SJPlaybackObservation.h"
#import "SJVideoPlayerPresentViewDefines.h"
#import "SJSubtitlesPromptControllerDefines.h"
#import "SJBarrageQueueControllerDefines.h"
#import "SJPromptDefines.h"
#import "SJBaseVideoPlayer.h"
#import <objc/message.h>
#import "SJRotationManager.h"
#import "SJDeviceVolumeAndBrightnessManager.h"
#import "SJVideoPlayerRegistrar.h"
#import "SJVideoPlayerPresentView.h"
#import "SJPlayModelPropertiesObserver.h"
#import "SJTimerControl.h"
#import "UIScrollView+ListViewAutoplaySJAdd.h"
#import "SJAVMediaPlaybackController.h"
#import "SJReachability.h"
#import "SJControlLayerAppearStateManager.h"
#import "SJFitOnScreenManager.h"
#import "SJFlipTransitionManager.h"
#import "SJPlayerView.h"
#import "SJFloatSmallViewController.h"
#import "SJEdgeFastForwardViewController.h"
#import "SJVideoDefinitionSwitchingInfo+Private.h"
#import "SJPopPromptController.h"
#import "SJPrompt.h"
#import "SJBaseVideoPlayerConst.h"
#import "SJSubtitlesPromptController.h"
#import "SJBaseVideoPlayer+TestLog.h"
#import "SJVideoPlayerURLAsset+SJSubtitlesAdd.h"
#import "SJBarrageQueueController.h"
#import "SJViewControllerManager.h"
#import "UIView+SJBaseVideoPlayerExtended.h"
#import <Masonry/Masonry.h>
#import "Masonry.h"

@interface SJBaseVideoPlayer (Logs)
+ (BOOL)playerLogs:(NSInteger)logs;
+ (BOOL)versionLogs:(NSInteger)logs;
+ (BOOL)setVideoGravityLogs:(NSInteger)logs;
+ (BOOL)videoGravityLogs:(NSInteger)logs;
+ (BOOL)atViewControllerLogs:(NSInteger)logs;
+ (BOOL)initLogs:(NSInteger)logs;
+ (BOOL)deallocLogs:(NSInteger)logs;
+ (BOOL)playerViewDidLayoutSubviewsLogs:(NSInteger)logs;
+ (BOOL)playerViewWillMoveToWindowLogs:(NSInteger)logs;
+ (BOOL)playerViewHittestforviewLogs:(NSInteger)logs;
+ (BOOL)presentViewDidLayoutSubviewsLogs:(NSInteger)logs;
+ (BOOL)_handleSingleTapLogs:(NSInteger)logs;
+ (BOOL)_handleDoubleTapLogs:(NSInteger)logs;
+ (BOOL)_handlePanDirectionStateTranslateLogs:(NSInteger)logs;
+ (BOOL)_handlePinchLogs:(NSInteger)logs;
+ (BOOL)setControlLayerDataSourceLogs:(NSInteger)logs;
+ (BOOL)viewControllerManagerLogs:(NSInteger)logs;
+ (BOOL)registrarLogs:(NSInteger)logs;
+ (BOOL)_setupViewsLogs:(NSInteger)logs;
+ (BOOL)_configAVAudioSessionLogs:(NSInteger)logs;
+ (BOOL)_postNotificationLogs:(NSInteger)logs;
+ (BOOL)_showOrHiddenPlaceholderImageViewIfNeededLogs:(NSInteger)logs;
+ (BOOL)_configGestureControlLogs:(NSInteger)logs;
+ (BOOL)_updateCurrentPlayingIndexPathIfNeededLogs:(NSInteger)logs;
+ (BOOL)touchedOnTheScrollViewLogs:(NSInteger)logs;

@end
