#import <UIKit/UIKit.h>
#import "SJFitOnScreenManagerDefines.h"
#import "SJRotationManagerDefines.h"
#import "SJVideoPlayerControlLayerProtocol.h"
#import "SJControlLayerAppearManagerDefines.h"
#import "SJFlipTransitionManagerDefines.h"
#import "SJVideoPlayerPlaybackControllerDefines.h"
#import "SJVideoPlayerURLAsset+SJAVMediaPlaybackAdd.h"
#import "SJPlayerGestureControlDefines.h"
#import "SJDeviceVolumeAndBrightnessManagerDefines.h"
#import "SJFloatSmallViewControllerDefines.h"
#import "SJEdgeFastForwardViewControllerDefines.h"
#import "SJVideoDefinitionSwitchingInfo.h"
#import "SJPopPromptControllerDefines.h"
#import "SJPlaybackObservation.h"
#import "SJVideoPlayerPresentViewDefines.h"
#import "SJSubtitlesPromptControllerDefines.h"
#import "SJBarrageQueueControllerDefines.h"
#import "SJPromptDefines.h"
#import "SJBaseVideoPlayer.h"
#import <objc/message.h>
#import "SJRotationManager.h"
#import "SJDeviceVolumeAndBrightnessManager.h"
#import "SJVideoPlayerRegistrar.h"
#import "SJVideoPlayerPresentView.h"
#import "SJPlayModelPropertiesObserver.h"
#import "SJTimerControl.h"
#import "UIScrollView+ListViewAutoplaySJAdd.h"
#import "SJAVMediaPlaybackController.h"
#import "SJReachability.h"
#import "SJControlLayerAppearStateManager.h"
#import "SJFitOnScreenManager.h"
#import "SJFlipTransitionManager.h"
#import "SJPlayerView.h"
#import "SJFloatSmallViewController.h"
#import "SJEdgeFastForwardViewController.h"
#import "SJVideoDefinitionSwitchingInfo+Private.h"
#import "SJPopPromptController.h"
#import "SJPrompt.h"
#import "SJBaseVideoPlayerConst.h"
#import "SJSubtitlesPromptController.h"
#import "SJBaseVideoPlayer+TestLog.h"
#import "SJVideoPlayerURLAsset+SJSubtitlesAdd.h"
#import "SJBarrageQueueController.h"
#import "SJViewControllerManager.h"
#import "UIView+SJBaseVideoPlayerExtended.h"
#import <Masonry/Masonry.h>
#import "Masonry.h"

@interface SJBaseVideoPlayer (ScrollViewLogs)
+ (BOOL)setFloatSmallViewControllerLogs:(NSInteger)logs;
+ (BOOL)floatSmallViewControllerLogs:(NSInteger)logs;
+ (BOOL)_resetFloatSmallViewControllerObserverLogs:(NSInteger)logs;
+ (BOOL)setAutoDisappearFloatSmallViewLogs:(NSInteger)logs;
+ (BOOL)autoDisappearFloatSmallViewLogs:(NSInteger)logs;
+ (BOOL)setPauseWhenScrollDisappearedLogs:(NSInteger)logs;
+ (BOOL)pauseWhenScrollDisappearedLogs:(NSInteger)logs;
+ (BOOL)setHiddenViewWhenScrollDisappearedLogs:(NSInteger)logs;
+ (BOOL)hiddenViewWhenScrollDisappearedLogs:(NSInteger)logs;
+ (BOOL)setResumePlaybackWhenScrollAppearedLogs:(NSInteger)logs;
+ (BOOL)resumePlaybackWhenScrollAppearedLogs:(NSInteger)logs;
+ (BOOL)isPlayOnScrollViewLogs:(NSInteger)logs;
+ (BOOL)isScrollAppearedLogs:(NSInteger)logs;
+ (BOOL)setPlayerViewWillAppearExeBlockLogs:(NSInteger)logs;
+ (BOOL)(__kindof SJBaseVideoPlayer * _Nonnull))playerViewWillAppearExeBlockLogs:(NSInteger)logs;
+ (BOOL)setPlayerViewWillDisappearExeBlockLogs:(NSInteger)logs;
+ (BOOL)(__kindof SJBaseVideoPlayer * _Nonnull))playerViewWillDisappearExeBlockLogs:(NSInteger)logs;

@end
