#import <SJBaseVideoPlayer/SJBaseVideoPlayer.h>
#import "SJBaseVideoPlayer.h"
#import "SJVideoPlayerSettings.h"
#import "SJVideoPlayerURLAsset+SJControlAdd.h"
#import "SJVideoPlayerFilmEditingCommonHeader.h"
#import "SJVideoPlayerFilmEditingConfig.h"
#import "SJControlLayerSwitcher.h"
#import "SJEdgeControlLayer.h"
#import "SJFilmEditingControlLayer.h"
#import "SJMoreSettingControlLayer.h"
#import "SJLoadFailedControlLayer.h"
#import "SJNotReachableControlLayer.h"
#import "SJFloatSmallViewControlLayer.h"
#import "SJSwitchVideoDefinitionControlLayer.h"
#import "SJVideoPlayer.h"
#import "UIView+SJVideoPlayerSetting.h"
#import "SJFilmEditingControlLayer.h"
#import "UIView+SJAnimationAdded.h"
#import <objc/message.h>
#import <SJBaseVideoPlayer/SJBaseVideoPlayer.h>
#import <SJBaseVideoPlayer/SJBaseVideoPlayerConst.h>
#import <SJBaseVideoPlayer/SJReachability.h>
#import "SJReachability.h"
#import "SJBaseVideoPlayer.h"
#import "SJBaseVideoPlayerConst.h"
#import <SJUIKit/SJAttributesFactory.h>
#import "SJAttributesFactory.h"

@interface SJVideoPlayer (Logs)
+ (BOOL)deallocLogs:(NSInteger)logs;
+ (BOOL)versionLogs:(NSInteger)logs;
+ (BOOL)playerLogs:(NSInteger)logs;
+ (BOOL)initLogs:(NSInteger)logs;
+ (BOOL)lightweightPlayerLogs:(NSInteger)logs;
+ (BOOL)_initLogs:(NSInteger)logs;
+ (BOOL)_initializeSwitcherLogs:(NSInteger)logs;
+ (BOOL)_initializeSwitcherObserverLogs:(NSInteger)logs;
+ (BOOL)_initializeAssetStatusObserverLogs:(NSInteger)logs;
+ (BOOL)_initializeSettingsRecorderLogs:(NSInteger)logs;
+ (BOOL)_initializeFloatSmallViewControllerObserverIfNeededLogs:(NSInteger)logs;
+ (BOOL)_initializeAppearManagerObserverLogs:(NSInteger)logs;
+ (BOOL)_updateCommonPropertiesLogs:(NSInteger)logs;
+ (BOOL)defaultEdgeControlLayerLogs:(NSInteger)logs;
+ (BOOL)defaultFilmEditingControlLayerLogs:(NSInteger)logs;
+ (BOOL)defaultMoreSettingControlLayerLogs:(NSInteger)logs;
+ (BOOL)defaultLoadFailedControlLayerLogs:(NSInteger)logs;
+ (BOOL)defaultNotReachableControlLayerLogs:(NSInteger)logs;
+ (BOOL)defaultFloatSmallViewControlLayerLogs:(NSInteger)logs;
+ (BOOL)defaultSwitchVideoDefinitionControlLayerLogs:(NSInteger)logs;
+ (BOOL)sj_switchingInfoObserverLogs:(NSInteger)logs;
+ (BOOL)_switchControlLayerIfNeededLogs:(NSInteger)logs;
+ (BOOL)clickedMoreButtonItemLogs:(NSInteger)logs;
+ (BOOL)clickedFilmEditingItemLogs:(NSInteger)logs;
+ (BOOL)clickedDefinitionButtonItemLogs:(NSInteger)logs;
+ (BOOL)_handleClickedBackButtonEventLogs:(NSInteger)logs;
+ (BOOL)_whetherToSupportOnlyOneOrientationLogs:(NSInteger)logs;
+ (BOOL)setFloatSmallViewControllerLogs:(NSInteger)logs;
+ (BOOL)floatSmallViewControllerLogs:(NSInteger)logs;
+ (BOOL)controlLayerDidselectassetLogs:(NSInteger)logs;
+ (BOOL)tappedBlankAreaOnTheControlLayerLogs:(NSInteger)logs;
+ (BOOL)backItemWasTappedForControlLayerLogs:(NSInteger)logs;
+ (BOOL)reloadItemWasTappedForControlLayerLogs:(NSInteger)logs;

@end
