#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "XHLaunchAdConfiguration.h"
#import "XHLaunchAdConst.h"
#import "XHLaunchImageView.h"
#import "XHLaunchAd.h"
#import "XHLaunchAdView.h"
#import "XHLaunchAdImageView+XHLaunchAdCache.h"
#import "XHLaunchAdDownloader.h"
#import "XHLaunchAdCache.h"
#import "FLAnimatedImage.h"
#import "XHLaunchAdController.h"

@interface XHLaunchAd (Logs)
+ (BOOL)setLaunchSourceTypeLogs:(NSInteger)logs;
+ (BOOL)setWaitDataDurationLogs:(NSInteger)logs;
+ (BOOL)imageAdWithImageAdConfigurationLogs:(NSInteger)logs;
+ (BOOL)imageAdWithImageAdConfigurationDelegateLogs:(NSInteger)logs;
+ (BOOL)videoAdWithVideoAdConfigurationLogs:(NSInteger)logs;
+ (BOOL)videoAdWithVideoAdConfigurationDelegateLogs:(NSInteger)logs;
+ (BOOL)downLoadImageAndCacheWithURLArrayLogs:(NSInteger)logs;
+ (BOOL)downLoadImageAndCacheWithURLArrayCompletedLogs:(NSInteger)logs;
+ (BOOL)downLoadVideoAndCacheWithURLArrayLogs:(NSInteger)logs;
+ (BOOL)downLoadVideoAndCacheWithURLArrayCompletedLogs:(NSInteger)logs;
+ (BOOL)removeAndAnimatedLogs:(NSInteger)logs;
+ (BOOL)checkImageInCacheWithURLLogs:(NSInteger)logs;
+ (BOOL)checkVideoInCacheWithURLLogs:(NSInteger)logs;
+ (BOOL)clearDiskCacheLogs:(NSInteger)logs;
+ (BOOL)clearDiskCacheWithImageUrlArrayLogs:(NSInteger)logs;
+ (BOOL)clearDiskCacheExceptImageUrlArrayLogs:(NSInteger)logs;
+ (BOOL)clearDiskCacheWithVideoUrlArrayLogs:(NSInteger)logs;
+ (BOOL)clearDiskCacheExceptVideoUrlArrayLogs:(NSInteger)logs;
+ (BOOL)diskCacheSizeLogs:(NSInteger)logs;
+ (BOOL)xhLaunchAdCachePathLogs:(NSInteger)logs;
+ (BOOL)cacheImageURLStringLogs:(NSInteger)logs;
+ (BOOL)cacheVideoURLStringLogs:(NSInteger)logs;
+ (BOOL)skipActionLogs:(NSInteger)logs;
+ (BOOL)setLaunchImagesSourceLogs:(NSInteger)logs;
+ (BOOL)shareLaunchAdLogs:(NSInteger)logs;
+ (BOOL)initLogs:(NSInteger)logs;
+ (BOOL)setupLaunchAdEnterForegroundLogs:(NSInteger)logs;
+ (BOOL)setupLaunchAdLogs:(NSInteger)logs;
+ (BOOL)setupImageAdForConfigurationLogs:(NSInteger)logs;
+ (BOOL)addSkipButtonForConfigurationLogs:(NSInteger)logs;
+ (BOOL)setupVideoAdForConfigurationLogs:(NSInteger)logs;
+ (BOOL)addSubViewsLogs:(NSInteger)logs;
+ (BOOL)setImageAdConfigurationLogs:(NSInteger)logs;
+ (BOOL)setVideoAdConfigurationLogs:(NSInteger)logs;
+ (BOOL)setWaitDataDurationLogs:(NSInteger)logs;
+ (BOOL)skipButtonClickLogs:(NSInteger)logs;
+ (BOOL)removeAndAnimatedLogs:(NSInteger)logs;
+ (BOOL)clickAndPointLogs:(NSInteger)logs;
+ (BOOL)commonConfigurationLogs:(NSInteger)logs;
+ (BOOL)startWaitDataDispathTiemrLogs:(NSInteger)logs;
+ (BOOL)startSkipDispathTimerLogs:(NSInteger)logs;
+ (BOOL)removeAndAnimateLogs:(NSInteger)logs;
+ (BOOL)removeAndAnimateDefaultLogs:(NSInteger)logs;
+ (BOOL)removeOnlyLogs:(NSInteger)logs;
+ (BOOL)removeLogs:(NSInteger)logs;
+ (BOOL)removeSubViewsExceptLaunchAdImageViewLogs:(NSInteger)logs;
+ (BOOL)deallocLogs:(NSInteger)logs;

@end
